# This file should be renamed to secrets.sls
secrets:
  DB_PASSWORD: XXXXXX
  SECRET_KEY: XXXXXX
  BROKER_PASSWORD: XXXXXX
  EMAIL_USER: XXXXXX
  EMAIL_PASSWORD: XXXXXX
  RECAPTCHA_PRIVATE_KEY = XXXXXX
